# Load required libraries
library(linkET)
library(ggplot2)
library(ggtext)
library(dplyr)
library(cols4all)

# Read environmental data file
env <- read.delim("env.txt", sep = "\t", header = TRUE, row.names = 1)

# Read ASV data file and remove species annotation information
species <- read.delim("feature_table_tax_rare.txt", sep = "\t", header = TRUE, row.names = 1)
species <- species[, -ncol(species)]
species <- t(species)

# Group samples
groups <- list(
  "1_5cm" = grep("\\.S[1-3]$", rownames(species), value = TRUE),
  "5_15cm" = grep("\\.Z[1-3]$", rownames(species), value = TRUE),
  "15_25cm" = grep("\\.X[1-3]$", rownames(species), value = TRUE)
)

# Calculate correlation coefficients and p-values for environmental factors
cor <- correlate(env, method = "pearson")
cor <- cor |> adjust_pvalue(adjust_method = "fdr")
corr <- cor %>% as_md_tbl()

# Perform Mantel tests for each group and combine results
mantel_results <- lapply(names(groups), function(group) {
  samples <- groups[[group]]
  env_subset <- env[rownames(env) %in% samples, , drop = FALSE]
  species_subset <- species[rownames(species) %in% samples, , drop = FALSE]
  mantel_test(species_subset, env_subset, mantel_fun = 'mantel',
              spec_select = list(group = 1:ncol(species_subset))) %>%
    mutate(Group = group)
})

mantel <- bind_rows(mantel_results)
mantel$spec <- mantel$Group # Rename spec column to match group column

# Assign new values for mantel r and p (set plot labels)
mantel2 <- mantel %>%
  mutate(r = cut(r, breaks = c(-Inf, 0.2, 0.4, 0.6, Inf),
                 labels = c("<0.2", "0.2-0.4", "0.4-0.6", ">=0.6")),
         p = cut(p, breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
                 labels = c("<0.001", "0.001-0.01", "0.01-0.05", ">= 0.05")))

# Create heatmap of environmental factor correlations
p4 <- qcorrplot(cor,
                grid_col = "grey50",
                grid_size = 0.2,
                type = "upper",
                diag = FALSE,
                width = 35,
                height = 15) +
  geom_square() +
  scale_fill_gradientn(colours = custom_colors,
                       limits = c(-1, 1))

p5 <- p4 +
  geom_mark(size = 4,
            only_mark = TRUE,
            sig_level = c(0.05, 0.01, 0.001),
            sig_thres = 0.05,
            colour = 'white')

# Add lines for Mantel test results
p6 <- p5 +
  geom_couple(data = mantel2,
              aes(colour = p, size = r),
              curvature = nice_curvature(by = 'to'), alpha = 0.6, label.size = 8)

p7 <- p6 +
  scale_size_manual(values = c(0.5, 1.2, 3)) + # Line thickness
  scale_colour_manual(values = c("#B22222", "#9370DB", "#32CD32", "grey35")) + # Line colors
  scale_linetype_manual(values = "solid") + # Line type set to solid
  # Modify legend
  guides(size = guide_legend(title = "Mantel r",
                             override.aes = list(colour = "grey35"),
                             order = 2),
         colour = guide_legend(title = "Mantel p",
                               override.aes = list(size = 3),
                               order = 1),
         fill = guide_colorbar(title = "Pearson r", order = 3),
         linetype = guide_legend(title = "Group")) +
  theme(
    axis.text = element_text(size = 16), # Axis text size
    legend.title = element_text(size = 18), # Legend title size
    legend.text = element_text(size = 14) # Legend text size
  )

# Save the figure
if (!dir.exists("mantel_heatmap")) {
  dir.create("mantel_heatmap")
}

pdf_filename <- paste0("mantel_heatmap/", "mantel_heatmap_mud.pdf")
png_filename <- paste0("mantel_heatmap/", "mantel_heatmap_mud.png")

ggsave(pdf_filename, p7, width = 35, height = 25, units = "cm")
ggsave(png_filename, p7, bg = "white", width = 35, height = 25, units = "cm")
