library(tidyverse)
library(openxlsx)
library(dplyr)

# Read and transpose the data
rawdata1 <- as.data.frame(t(read.table("feature_table_tax_rare.txt", 
                                       header = TRUE, row.names = 1, sep = "\t")))

# Add a month column (1 to 24, 3 samples each)
rawdata2 <- cbind(month = rep(1:24, each = 3), rawdata1)

# Group by month and sum the values for identical months
data <- rawdata2 %>%
  group_by(month) %>%
  summarise_all(sum)

# Transpose the data after summarization
tdata <- as.data.frame(t(data))

# Create a directory to save intermediate files, if it doesn't exist
if (!file.exists("interfile")) {
  dir.create("interfile")
}

# Save the transposed data to a text file
write.table(tdata, file = "interfile/feature_table_tax_rare_inter.txt", 
            sep = "\t", row.names = TRUE, quote = FALSE, col.names = FALSE)

# Running MetaCycle Analysis

library(MetaCycle)

# Run meta2d for periodicity detection using MetaCycle
meta2d(infile = "interfile/feature_table_tax_rare_inter.txt", filestyle = "txt",
       outdir = "metacycle_result", timepoints = rep(seq(1, 24, by = 1), each = 1), 
       ARSdefaultPer = 12, minper = 10, maxper = 14,
       cycMethod = c("JTK", "LS"), outIntegration = "both")
