
```{r}
library(dplyr)
library(tidyverse)
library(ggridges)
library(openxlsx)

# 整合两个文件，提取lomb结果中PNmax > 10, p <0.05的物种和jtk中adj.p<0.05的物种

# Read in the files
lomb <- read.xlsx("lomb_results_noreplicate_asv.xlsx", colNames = TRUE, rowNames = T)

jtk <- read.table("JTKresult_feature_table_tax_rare_inter.txt", header = TRUE, sep = "\t", check.names = FALSE, row.names = 1)

feature_table <- read.table("feature_table_tax_rare.txt", header = TRUE, sep = "\t", check.names = FALSE, row.names = 1)

# 过滤
filtered_lomb <- lomb %>%
  filter(PNmax > 0.1, Pval < 0.05)

filtered_jtk <- jtk %>%
  filter(ADJ.P < 0.05)

# 取节律性ASV的交集
common_rows <- intersect(rownames(filtered_lomb), rownames(filtered_jtk))

# Subset the feature table data frame with the selected rows
extracted_feature_data <- feature_table[common_rows, ]

if (!dir.exists("plot")) {
  dir.create("plot")
}

# 将节律性ASV的丰度表保存到本地
write.table(extracted_feature_data, "plot/final_rhythmic_ASV.txt", sep = "\t", quote = FALSE, col.names = NA)
```


```{r}
# 将新数据框extracted_feature_data中的同一月份的物种丰度合并得到summed_data。

# Initialize an empty data frame to store the summed data
summed_data <- data.frame(row.names = rownames(extracted_feature_data))

# Function to generate new column names based on your pattern
generate_column_names <- function(prefix, num_columns) {
  months <- c("2020.11", "2020.12", "2021.01", "2021.02", "2021.03", "2021.04", "2021.05", "2021.06", "2021.07", "2021.08", "2021.09", "2021.10", "2021.11", "2021.12", "2022.01", "2022.02", "2022.03", "2022.04", "2022.05", "2022.06", "2022.07", "2022.08", "2022.09", "2022.10")
  rep(months, length.out = num_columns)
}

# Sum every three columns
for (i in seq(1, ncol(extracted_feature_data), by = 3)) {
  # Ensure not to go beyond the number of columns
  end_col <- min(i+2, ncol(extracted_feature_data))
  
  # Sum the columns and add as a new column to the summed_data
  column_sum <- rowSums(extracted_feature_data[, i:end_col, drop = FALSE])
  summed_data <- cbind(summed_data, column_sum)
}

# Rename the columns as specified
colnames(summed_data) <- generate_column_names("mud", ncol(summed_data))

```


```{r}
# 将 “每行代表一个物种” 改为 “每列代表一个物种”。然后将month列改为日期格式，
# 方便后面绘制折线图。最后绘图。

# 获取物种列表
species_list <- rownames(summed_data)

# 创建一个新的列以存储物种名称
summed_data$Species <- rownames(summed_data)

# 转换数据为长格式(就是从行的形式转变为列的形式)
long_data <- summed_data %>%
  pivot_longer(cols = -Species, names_to = "Month", values_to = "Abundance")

# 假设 Month 列是字符串日期，例如 "2020.11"
long_data$Month <- as.Date(paste0(long_data$Month, ".01"), format = "%Y.%m.%d")

# 使用strsplit函数分割字符串并提取最后一个分号后面的内容
long_data$Species <- sapply(strsplit(long_data$Species, ";"), function(x) tail(x, 1))

# 循环创建几个个数据框，分别包含前20个物种的数据(共1180个)
num_species = 136

# 创建一个包含所有数据框的列表
data_frames_list <- list()
for (i in 1:6) {
  start_index <- (i - 1) * 20 + 1
  end_index <- min(i * 20, num_species)
  selected_data <- subset(long_data, Species %in% unique(long_data$Species)[start_index:end_index])
  data_frames_list[[i]] <- selected_data
}

# 创建一个包含所有图的列表
plots_list <- list()
for (i in 1:6) {
  p <- ggplot(data = data_frames_list[[i]], mapping = aes(x = Month, y = Abundance, 
                                                           color = Species, fill = Species)) +
    geom_line() +
    geom_ribbon(aes(ymin = 0, ymax = Abundance), alpha = 0.2) +
    scale_x_date(date_labels = "%Y.%m", date_breaks = "3 month") +
    facet_wrap(.~ Species, scales = "free_y", ncol = 5) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), 
          axis.text.y = element_text(size = 15), 
          axis.title.x = element_text(size = 30), 
          axis.title.y = element_text(size = 30)) +
    theme(strip.text = element_text(size = 15)) +
    guides(color = "none", fill = "none")
  
  plots_list[[i]] <- p
  
  # 生成文件名
  pdf_filename <- paste0("plot/", "ASV_plot_", i, ".pdf")
  png_filename <- paste0("plot/", "ASV_plot_", i, ".png")
  
  # 保存图形到PDF和PNG文件
  ggsave(pdf_filename, p, width = 55, height = 25, units = "cm")
  ggsave(png_filename, p, bg = "white", width = 55, height = 25, units = "cm")
}

# 绘制不足20个子图的图
rest_data <- subset(long_data, Species %in%
                          unique(long_data$Species)[121:136])

p <- ggplot(data = rest_data, mapping = aes(x = Month, y = Abundance, 
                                                           color = Species, fill = Species)) +
    geom_line() +
    geom_ribbon(aes(ymin = 0, ymax = Abundance), alpha = 0.2) +
    scale_x_date(date_labels = "%Y.%m", date_breaks = "3 month") +
    facet_wrap(.~ Species, scales = "free_y", ncol = 5, nrow = 4) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), 
          axis.text.y = element_text(size = 15), 
          axis.title.x = element_text(size = 30), 
          axis.title.y = element_text(size = 30)) +
    theme(strip.text = element_text(size = 15)) +
    guides(color = "none", fill = "none")

# 生成文件名
pdf_filename <- paste0("plot/", "ASV_plot_", "7", ".pdf")
png_filename <- paste0("plot/", "ASV_plot_", "7", ".png")
  
# 保存图形到PDF和PNG文件
ggsave(pdf_filename, p, width = 55, height = 25, units = "cm")
ggsave(png_filename, p, bg = "white", width = 55, height = 25, units = "cm")
```

```{r}
# 绘制不同样式的图

# 1 绘制折线图，填充为灰色
#p <- ggplot(data = long_data, mapping = aes(x = Month, y = Abundance, color = Species)) +
#  geom_line() +
#  geom_ribbon(aes(ymin = 0, ymax = Abundance), alpha = 0.2) +  # 添加填充颜色
#  scale_x_date(date_labels = "%Y.%m", date_breaks = "1 month") +
#  theme_minimal() +
#  facet_grid(Species ~ ., scales = "free_y") +
#  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# 绘制折线图，填充为对应分组的颜色
#p <- ggplot(data = long_data, mapping = aes(x = Month, y = Abundance, color = Species, fill = #Species)) +
#  geom_line() +
#  geom_ribbon(aes(ymin = 0, ymax = Abundance), alpha = 0.2) +
#  scale_x_date(date_labels = "%Y.%m", date_breaks = "1 month") +
#  theme_minimal() +
#  facet_grid(Species ~ ., scales = "free_y") +
#  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}

#p <- p +
#  theme(
#    legend.position = "bottom",  # 将图例放在底部
#    legend.box = "vertical",     # 将图例放在一列
#    legend.text = element_text(size = 5)  # 调整图例文字大小
#  )

```




